import "~/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import { Roboto } from 'next/font/google'
import SessionProviderWrapper from "../_components/SessionProviderWrapper";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "DEV Community",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/devto-logo.png" }],
};

export default function AuthLayout({
   children,
 }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={roboto.className}>
    <body className="bg-gray-100 h-screen w-full overflow-hidden">
    <SessionProviderWrapper>
      <TRPCReactProvider>
        <main className="">
          {children}
        </main>
      </TRPCReactProvider>
    </SessionProviderWrapper>
    </body>
    </html>
  );
}
